#!/usr/bin/env bash
# display information about subdomains.
if [ $# -eq 1 ]
	then
    	for DOM in 'www' 'lb-01' 'web-01' 'web-02'
    		do
			URL="$DOM.$1"
			A=$(dig $URL | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
			IP=$(dig $URL | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
			echo "The subdomain $DOM $A record and points to $IP"
        	done
elif [ $# -eq 2 ]
	then
        		URL="$2.$1"
                        A=$(dig $URL | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
                        IP=$(dig $URL | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
                        echo "The subdomain $2 $A record and points to $IP"
fi
