#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, in the 9 time add "hi"
i=1
while [ $i -le 10 ]
do
	echo Holberton School
	if [ $i -eq 9 ]
	then
		echo hi
	fi
        let i+=1
done 
