#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
count=59
hour=-1

while [ $count -le 60 ]
do
        let count+=1
	case $count in
	60) let hour+=1
	    echo "Hour: ${hour}"
            count=0
            
            
	;;
	59) echo $count
		if [ $hour -eq 12 ]
	    then
	       break
	fi
	;;
	*) echo $count
	;;
	esac
done
